### ISSUE TITLE
Attempting to parse decimal throws error within MAP statement.

### ISSUE THREAD

**Issue by RyanFleck** [Xalgorithms/xa-rules#13]
When performing a MAP operation on a table, `multiply(0.01, transaction:subtotal)` throws the following error:
```
Failed to match sequence (STATEMENT (SPACE? STATEMENT){0, } SPACE?) at line 1 char 337.
`- Extra input after last repetition at line 1 char 337.
   `- Expected at least 1 of \\s at line 1 char 337.
      `- Failed to match \\s at line 1 char 337.
```
 `multiply(divide(1,100), transaction:subtotal)` works in the meantime to process a percentage:

```
MAP table:apply_vat
  USING EffectivePrice = add(1, multiply(divide(1, 100), @HST));
```

This issue can be replicated using the .rule file present in this archive. [tax.zip](https://github.com/Xalgorithms/lib-rules-parse-ruby/files/2613592/tax.zip)

**Comment by karfai** [comment]
The [compute platform](https://github.com/Xalgorithms/interlibr) as it is currently implemented [has changed](https://development.xalgorithms.org/architecture/core.architecture/). This is no longer relevant.
