### ISSUE TITLE
Support for META_URL.

### ISSUE THREAD

**Issue by RyanFleck** [Xalgorithms/xa-rules#14]
When attempting to run a rule, the inclusion of a URL field causes the parser to throw an exception.

```
META
  VERSION "0.0.3"
  RUNTIME "0.4.0"
  CRITICALITY "experimental"
  URL "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/charge-gst/charge-gst-hst.html";
```

**Comment by karfai** [comment]
The [compute platform](https://github.com/Xalgorithms/interlibr) as it is currently implemented [has changed](https://development.xalgorithms.org/architecture/core.architecture/). This is no longer relevant.
