### ISSUE TITLE
Clearer exception could be thrown when single-quote is encountered.

### ISSUE THREAD

**Issue by RyanFleck** [Xalgorithms/xa-rules#15]
Accidental use of single-quotes currently results in `Failed to match sequence` errors.

A more useful error could me thrown informing the author to replace the single quote with a double.

**Comment by karfai** [comment]
The [compute platform](https://github.com/Xalgorithms/interlibr) as it is currently implemented [has changed](https://development.xalgorithms.org/architecture/core.architecture/). This is no longer relevant.
